defaults:
  - /data_new/sources
  - /data_new/population@population: agri_growth_set

_target_: src.data_new.datamodule.Corpus

name: agri_growth_set

sources:
  - ${data_new.sources.agri_growth}

reference_date: "2024-11-01"
threshold: "2025-01-01"
