defaults:
  - /data_new/corpus@corpus: online2
  - /data_new/vocabulary@vocabulary: online2
  - /task@task: online2_mlm

_target_: src.data_new.datamodule.L2VDataModule
batch_size: 4
num_workers: 0
persistent_workers: false
pin_memory: false
