defaults:
  - /data_new/sources

_target_: src.data_new.populations.agri_fruiting.AgriFruitingPopulation

name: agri_fruiting_set
growth_data: ${data_new.sources.agri_growth_finetune}
min_events: 5
seed: 2023
train_val_test: [0.7, 0.15, 0.15]
